### ISSUE TITLE
Hintergrundbild verschwindet / ist nicht sichtbar

### ISSUE THREAD

**Issue by jwende** [MyHomeMyData/iob.vis.vitocal250#1]
Nach ein paar Tagen verschwindet auf einmal das Hintergrundbild - weder bei aktiver noch bei inaktiver WP wird etwas angezeigt.

**Comment by MyHomeMyData** [comment]
Schau bitte mal, welchen Wert 2351_HeatPumpCompressor hat. Daraus wird abgeleitet, welches Bild angezeigt wird (0 -> Kompressor aus, 1 -> Kompressor ein). Andere Werte als 0 und 1 habe ich bisher nicht gesehen.

**Comment by jwende** [comment]
Da kommt im Augenblick 0,0 … 
PS: kann ich das auch in jarvis importieren?

**Comment by MyHomeMyData** [comment]
Du verwendest vermutlich eine neuere Version der open3e Codecs. Statt 0 wird jetzt 0,0 übertragen und das erkennt die Vis anscheinend nicht als 0.
Abhilfe: In der Objekt-Eigenschaften von 2351_HeatPumpCompressor auf "Number" und "Step=1" umstellen:
![image](https://github.com/MyHomeMyData/iob.vis.vitocal250/assets/144950531/403552a7-a5d8-406b-bd9d-b19672c4c975)


In **jarvis** kannst Du das über iFrame einbinden. Die Vis-Darstellung aufrufen die URL im Browser kopieren und in das iFrame-Widget als URL einfügen.

**Comment by jwende** [comment]
Danke - das war es - Boolean geht auch!

**Comment by jwende** [comment]
Bis demnächst
